# Copyright (c) 2022 Graphcore Ltd. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ----------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------


vit_base_pod16: &vit_base_pod16

  # Execution
  half: True
  batch_size: 2
  ga: 64
  replica: 2
  epochs: 100
  device: ipu
  num_workers: 16
  output: checkpoint_dino_vit_base
  log: loss.log
  local_crops_number: 8
  local_crops_scale: [0.05, 0.4]
  saveckp_freq: 1
  print_freq: 10
  async_type: async
  use_clip: False
  global_crops_scale: [0.4, 1]
  warmup_epochs: 10

  # Model
  arch: vit_base
  pipeline: [1, 2, 2, 2, 2, 2, 1, 0]
  drop_path_rate: 0.1
  momentum_teacher: 0.996
  warmup_teacher_temp: 0.04
  teacher_temp: 0.04
  warmup_teacher_temp_epochs: 0

  # Optimizer
  optimizer: 'adamw'
  lr: 0.0005
  loss_scale: 128.0
  eps: 1e-5

  # Dataset
  data_path: './data/imagenet1k/train'

# ----------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------

vit_base_pod64: &vit_base_pod64

  # Execution
  half: True
  batch_size: 4
  ga: 400
  epochs: 100
  device: ipu
  num_workers: 32
  output: checkpoint_dino_vit_base
  log: loss.log
  local_crops_number: 8
  local_crops_scale: [0.05, 0.4]
  saveckp_freq: 1
  print_freq: 10
  async_type: rebatch
  rebatched_worker_size: 800
  use_clip: False
  global_crops_scale: [0.4, 1]
  warmup_epochs: 10

  # Model
  arch: vit_base
  pipeline: [1, 2, 2, 2, 2, 2, 1, 0]
  drop_path_rate: 0.1
  momentum_teacher: 0.996
  warmup_teacher_temp: 0.04
  teacher_temp: 0.04
  warmup_teacher_temp_epochs: 0

  # Optimizer
  optimizer: 'adamw'
  lr: 0.002
  loss_scale: 128.0
  eps: 1e-5

  # Dataset
  data_path: './data/imagenet1k/train'


# ----------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------

vit_base_pod256: &vit_base_pod256

  # Execution
  half: True
  batch_size: 4
  ga: 400
  epochs: 100
  device: ipu
  num_workers: 32
  output: checkpoint_dino_vit_base
  log: loss.log
  local_crops_number: 8
  local_crops_scale: [0.05, 0.4]
  saveckp_freq: 1
  print_freq: 10
  async_type: rebatch
  rebatched_worker_size: 200
  use_clip: False
  global_crops_scale: [0.4, 1]
  warmup_epochs: 10

  # Model
  arch: vit_base
  pipeline: [1, 2, 2, 2, 2, 2, 1, 0]
  drop_path_rate: 0.1
  momentum_teacher: 0.996
  warmup_teacher_temp: 0.04
  teacher_temp: 0.04
  warmup_teacher_temp_epochs: 0

  # Optimizer
  optimizer: 'adamw'
  lr: 0.002
  loss_scale: 128.0
  eps: 1e-5

  # Dataset
  data_path: './data/imagenet1k/train'

# ----------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------

vit_small_pod16: &vit_small_pod16

  # Execution
  batch_size: 2
  ga: 64
  replica: 4
  epochs: 100
  device: ipu
  num_workers: 16
  output: checkpoint_dino_vit_small
  log: loss.log
  local_crops_number: 6
  local_crops_scale: [0.05, 0.25]
  saveckp_freq: 1
  print_freq: 10
  async_type: async
  use_clip: True
  global_crops_scale: [0.25, 1.0]
  warmup_epochs: 10

  # Model
  arch: vit_small
  pipeline: [4, 4, 4, 0]
  drop_path_rate: 0.1
  momentum_teacher: 0.996
  warmup_teacher_temp: 0.04
  teacher_temp: 0.04
  warmup_teacher_temp_epochs: 0

  # Optimizer
  optimizer: 'adamw'
  lr: 0.0005
  min_lr: 1e-05
  loss_scale: 128.0
  eps: 1e-5

  # Dataset
  data_path: './data/imagenet1k/train'
# ----------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------
vit_tiny_pod16: &vit_tiny_pod16

  # Execution
  batch_size: 2
  ga: 64
  replica: 4
  epochs: 100
  device: ipu
  num_workers: 16
  output: checkpoint_dino_vit_tiny
  log: loss.log
  local_crops_number: 6
  saveckp_freq: 1
  print_freq: 10
  async_type: normal
  use_clip: False
  warmup_epochs: 10

  # Model
  arch: vit_tiny
  pipeline: [4, 4, 4, 0]
  drop_path_rate: 0.1
  momentum_teacher: 0.996

  # Optimizer
  optimizer: 'adamw'
  lr: 0.0005
  loss_scale: 128.0
  eps: 1e-5

  # Dataset
  data_path: './data/imagenet1k/train'
# ----------------------------------------------------------------------------------
