common: &common
  precision: "16.16"
  replicas: 1
  device_iterations: 128
  half_partial: true
  norm_type: batch
  eight_bit_io: true
  normalization_location: ipu


resnet50-mk1:
  <<: *common
  model: resnet50
  batch_size: 8


resnet50-mk2:
  <<: *common
  model: resnet50
  batch_size: 90


efficientnet-b0-mk1:
  <<: *common
  model: efficientnet-b0
  batch_size: 11
  

efficientnet-b0-mk2:
  <<: *common
  model: efficientnet-b0
  batch_size: 40